name: "Feature Request"
description: "Suggest an idea or enhancement for Traceroot."
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!
        Please help us understand your use case and how this feature would help.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "What problem are you trying to solve?"
      placeholder: "Describe the problem or need."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "Describe the solution you'd like."
      placeholder: "How would you like this to work?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you considered any alternative solutions or workarounds?"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "Add any other context, screenshots, or references here."
  - type: checkboxes
    id: willing_to_help
    attributes:
      label: Willing to Help Implement?
      description: "Would you like to work on or help with this feature?"
      options:
        - label: I would like to work/help with this
